### PR TITLE
Fix coverage with coveralls

### PR DESCRIPTION
**Pull request by 3imed-jaberi**
- add coverage config to integrate with `coveralls` and `codecov` (fix link to coveralls.io). 
- add me to contributors.
- use `async/await` over `then()` > ES2017.
- support node 8+ engine.

> @niftylettuce , you can publish the next release and also add `CHANGELOG` file.

### CODE REVIEW

**Comment by niftylettuce** [comment]
@3imed-jaberi I merged this, but tests are failing right now:

```sh
  50 passing (1s)
  3 failing

  1) Disk Storage should process parser/form-data POST request:

      Uncaught AssertionError [ERR_ASSERTION]: 1778 == 1803
      + expected - actual

      -1778
      +1803

      at test/disk-storage.js:46:14
      at Immediate._onImmediate (test/_util.js:37:11)
      at processImmediate (internal/timers.js:458:21)

  2) Disk Storage should process multiple files:

      Uncaught AssertionError [ERR_ASSERTION]: 122 == 128
      + expected - actual

      -122
      +128

      at test/disk-storage.js:120:14
      at Immediate._onImmediate (test/_util.js:37:11)
      at processImmediate (internal/timers.js:458:21)

  3) Memory Storage should process multiple files:

      Uncaught AssertionError [ERR_ASSERTION]: 122 == 128
      + expected - actual

      -122
      +128

      at test/memory-storage.js:105:14
      at Immediate._onImmediate (test/_util.js:37:11)
      at processImmediate (internal/timers.js:458:21)



error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by 3imed-jaberi** [comment]
@niftylettuce, plz wait i try to make test pass on the pipeline, you know the pb here #28 .. 

> tests are failing right now

I was still making the test pass, you know the pb #28, i will open now new pr and make every thing work 100%

**Comment by niftylettuce** [comment]
can you join our Slack channel for Lad?

https://lad.js.org -> there is a badge to join at top

**Comment by 3imed-jaberi** [comment]
> can you join our Slack channel for Lad?
> 
> https://lad.js.org -> there is a badge to join at top

yes, I am coming

**Pull request merged**
